// https://www.listchallenges.com/the-ultimate-list-of-disney-characters

const set = new Set([
  'Mickey Mouse',
  'Minnie Mouse',
  'Goofy',
  'Donald Duck',
  'Pluto',
  'Daisy Duck',
  'Scrooge McDuck',
  'Launchpad McQuack',
  'Huey, Dewey and Louie',
  'Bambi (1942)',
  'Thumper',
  'Flower',
  'Faline',
  'Tinker Bell',
  'Peter Pan',
  'Wendy',
  'John Darling',
  'Michael Darling',
  'Captain Hook',
  'Tiger Lily',
  'Mr. Smee',
  'Alice',
  'Mad Hatter',
  'March Hare',
  'Queen of Hearts',
  'Cheshire Cat',
  'Kuzco',
  'Yzma',
  'Kronk',
  'Pacha',
  'Snow White',
  'Dopey',
  'Doc',
  'Sleepy',
  'Sneezy',
  'Bashful',
  'Happy',
  'Grumpy (1930)',
  'Evil Queen',
  'Prince Charming',
  'Cinderella (1950)',
  'Gus Gus',
  'Jaq Jaq',
  'Fairy Godmother',
  'Lady Tremaine',
  'Anastasia',
  'Drizella',
  'Pinocchio (1940)',
  'Jiminy Cricket',
  'Gepetto',
  'Honest John and Gideon',
  'Stromboli (1950)',
  'Blue Fairy',
  'Pocahontas (1995)',
  'John Smith',
  'Kocoum',
  'Meeko',
  'Flit',
  'Percy',
  'Governor Ratcliffe',
  'Princess Aurora (2005)',
  'Flora',
  'Fauna',
  'Merryweather',
  'Prince Philip',
  'Maleficent (2014)',
  'Merida',
  'Queen Elinor',
  'Rapunzel (2009)',
  'Flynn Rider',
  'Mother Gothel',
  'Pascal',
  'Mowgli',
  'Baloo',
  'Bagheera',
  'Shere Khan',
  'Kaa',
  'Sir Hiss',
  'Robin Hood (1973)',
  'Little John',
  'Sheriff of Nottingham',
  'Prince John',
  'Maid Marian',
  'Duchess',
  'Marie',
  'Toulouse',
  'Berlioz',
  "Thomas O'Malley",
  'Pongo',
  'Perdita',
  'Cruella De Vil',
  'Winnie the Pooh',
  'Tigger',
  'Kanga & Roo',
  'Eeyore',
  'Piglet (1977)',
  'Christopher Robin',
  'Lumpy',
  'Owl (2003)',
  'Rabbit',
  'Mulan (1998)',
  'Mushu',
  'Shan Yu',
  'Li Shang',
  'Panchito Pistoles',
  'Jose Carioca',
  'Belle',
  'Beast',
  'Gaston',
  'Maurice',
  'Le Fou',
  'Lumiere',
  'Cogsworth',
  'Mrs Potts',
  'Chip',
  'Chip',
  'Dale',
  'Dumbo',
  'Timothy Q Mouse',
  'Aladdin',
  'Jasmine',
  'Jafar',
  'Iago',
  'Genie (2010)',
  'Abu',
  'Hercules (1997)',
  'Phil',
  'Pegasus',
  'Zeus',
  'Hades',
  'Megara',
  'Esmeralda',
  'Djali',
  'Quasimodo',
  'Clopin Trouillefou',
  'Judge Claude Frollo',
  'Laverne',
  'Hugo',
  'Victor',
  'Lilo',
  'Stitch',
  'Nani Pelekai',
  'Jumba',
  'Max Goof',
  'Horace Horsecollar',
  'Clarabelle Cow',
  'Ariel',
  'Flounder',
  'Scuttle',
  'King Triton',
  'Prince Eric',
  'Sebastian',
  'Ursula (1961)',
  'Lady',
  'Tramp',
  'Tarzan (1999)',
  'Jane',
  'Pete',
  'Mortimer Mouse',
  'Princess Eilonwy',
  'Periwinkle',
  'Fawn',
  'Silvermist',
  'Vidia',
  'Iridessa',
  'Rosetta (1999)',
  'Simba',
  'Nala',
  'Timon',
  'Pumbaa',
  'Scar',
  'Mufasa the Lion King',
  'Zazu',
  'Brer Rabbit',
  'Brer Fox',
  "Br'er Bear",
])

export default [...set]
